
UNIT_TYPE -> PROCEDURE [TOKEN_SLASH];

PROCEDURE -> TOKEN_KEYWORD_CREATE [TOKEN_KEYWORD_OR TOKEN_KEYWORD_REPLACE]
 TOKEN_KEYWORD_PROCEDURE TOKEN_IDENTIFIER {TOKEN_KEYWORD_IS | TOKEN_KEYWORD_AS}
 TOKEN_KEYWORD_BEGIN PROCEDURE_STATEMENTS TOKEN_KEYWORD_END [TOKEN_IDENTIFIER];

PROCEDURE_STATEMENTS -> [PROCEDURE_STATEMENTS] PROCEDURE_STATEMENT;

PROCEDURE_STATEMENT -> [TOKEN_IDENTIFIER TOKEN_PERIOD] TOKEN_IDENTIFIER
 TOKEN_LEFT_PAREN [TOKEN_STRING] TOKEN_RIGHT_PAREN TOKEN_SEMICOLON;
